config/routes.rb
Rails.application.routes.draw do
  resources :notes, only: [:new, :destroy, :create, :edit, :update]
  resources :cases
  resources :resources
  resources :social_workers
  resources :clients
  root 'sessions#welcome'
  get '/welcome', to: 'sessions#welcome'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'
  post '/cases/:id/close', to: 'cases#close'
  get '/dashboard', to: 'sessions#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    @cases = Case.all
  end

  def show
    @case = Case.find(params[:id])
  end

  def new
    @case = Case.new
    @social_workers = SocialWorker.all
    @clients = Client.all
    @resources = Resource.all
  end

  def create
    @case = Case.new(case_params)
    if @case.valid?
      @case.save
      redirect_to case_path(@case)
    else
      flash[:errors] = @case.errors.full_messages
      redirect_to new_case_path
    end
  end

  def edit
    @case = Case.find(params[:id])
    @social_workers = SocialWorker.all
    @clients = Client.all
    @resources = Resource.all
  end

  def update
    @case = Case.find(params[:id])
    @case.update(case_params)
    if @case.valid?
      @case.save
      redirect_to case_path(@case)
    else
      flash[:errors] = @case.errors.full_messages
      redirect_to edit_case_path
    end
  end

  def close
    @case = Case.find(params[:id])
    @case.close_case
    @case.save
    redirect_to case_path(@case)
  end

  private

  def case_params
    params.require(:case).permit(:client_id, :social_worker_id, :resource_id, :focus)
  end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/views/cases/edit.html.erb
<h1 class="display-1 text-center">Edit Case</h1>

<div class="container">
    <form action="/cases/<%=@case.id%>" accept-charset="UTF-8" data-remote="true" method="post">
    <input type="hidden" name="_method" value="patch">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
        <div class="alert alert-danger" role="alert">
            <%= error %>
        </div>
        <% end %>
        <% end %>
        <div class="form-group">
            <label for="case_client_id">Select a Client</label>
            <select class="form-control" id="case_client_id" name="case[client_id]">
                <option value="">Select a Client</option>
                <% @clients.each do |client| %>
                <% if @case.client == client %>
                <option selected="selected" value="<%=client.id%>"><%=client.name%></option>
                <% else %>
                <option value="<%=client.id%>"><%=client.name%></option>
                <% end %>
                <% end %>
            </select>
        </div>
        <div class="form-group">
            <label for="case_social_worker_id">Select a Social Worker</label>
            <select class="form-control" id="case_social_worker_id" name="case[social_worker_id]">
                <option value="">Select a Social Worker</option>
                <% @social_workers.each do |sw| %>
                <% if @case.social_worker == sw %>
                <option selected="selected" value="<%=sw.id%>"><%=sw.name%></option>
                <% else %>
                <option value="<%=sw.id%>"><%=sw.name%></option>
                <% end %>
                <% end %>
            </select>
        </div>
        <div class="form-group">
            <label for="case_Resource_id">Select a Resource</label>
            <select class="form-control" id="case_resource_id" name="case[resource_id]">
                <option value="">Select a Resource</option>
                <% @resources.each do |resource| %>
                <% if @case.resource == resource %>
                <option selected="selected" value="<%=resource.id%>"><%=resource.name%></option>
                <% else %>
                <option value="<%=resource.id%>"><%=resource.name%></option>
                <% end %>
                <% end %>
            </select>
        </div>
        <div class="form-group">
            <label for="case_focus">Focus</label>
            <input type="text" class="form-control" name="case[focus]" id="case_focus" placeholder="Focus" value="<%=@case.focus%>">
        </div>
        <input class="btn btn-primary" type="submit" name="commit" value="Save Changes" data-disable-with="Save Changes" />
    </form>
</div>

app/views/cases/index.html.erb
<h1 class="display-1 text-center">All Cases</h1>

<style>
.card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
}

.btn btn-primary {
  border-radius 25px
}

</style>

<div class="container">
    <div class="row">
            <% @cases.each do |c| %>
            <div class="col-sm-4">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="<%=c.client.image_url%>" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Case #<%=c.id%></h5>
                        <p class="card-text">
                        <p><strong>Client:</strong> <%=c.client.name%></p>
                        <p><strong>Social Worker:</strong> <%=c.social_worker.name%></p>
                        <p><strong>Focus:</strong> <%=c.focus%></p>
                        </p>
                        <a href="/cases/<%=c.id%>" class="btn btn-primary">View Case</a>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>

app/views/cases/new.html.erb
<h1 class="display-1 text-center">Create New Case</h1>

<div class="container">
    <form action="/cases" accept-charset="UTF-8" data-remote="true" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
        <div class="alert alert-danger" role="alert">
            <%= error %>
        </div>
        <% end %>
        <% end %>
        <div class="form-group">
            <label for="case_client_id">Select a Client</label>
            <select class="form-control" id="case_client_id" name="case[client_id]">
                <option value="">Select a Client</option>
                <% @clients.each do |client| %>
                <option value="<%=client.id%>"><%=client.name%></option>
                <% end %>
            </select>
        </div>
        <div class="form-group">
            <label for="case_social_worker_id">Select a Social Worker</label>
            <select class="form-control" id="case_social_worker_id" name="case[social_worker_id]">
                <option value="">Select a Social Worker</option>
                <% @social_workers.each do |sw| %>
                <option value="<%=sw.id%>"><%=sw.name%></option>
                <% end %>
            </select>
        </div>
        <div class="form-group">
            <label for="case_Resource_id">Select a Resource</label>
            <select class="form-control" id="case_resource_id" name="case[resource_id]">
                <option value="">Select a Resource</option>
                <% @resources.each do |resource| %>
                <option value="<%=resource.id%>"><%=resource.name%></option>
                <% end %>
            </select>
        </div>
        <div class="form-group">
            <label for="case_focus">Focus</label>
            <input type="text" class="form-control" name="case[focus]" id="case_focus" placeholder="Focus" value="<%=@case.focus%>">
        </div>
        <input class="btn btn-primary" type="submit" name="commit" value="Create Case" data-disable-with="Create Case" />
    </form>
</div>

app/views/cases/show.html.erb
<h1 class="display-1 text-center">Case Details</h1>

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <u>
                <h1 class="display-4 text-left">Client</h1>
            </u>
            <img src="<%=@case.client.image_url%>" class="img-fluid img-thumbnail" alt="Client Picture">
            <h3><%= link_to @case.client.name, client_path(@case.client)%></h3>
        </div>
        <div class="col-sm-6">
            <u>
                <h1 class="display-4 text-left">Social Worker</h1>
            </u>
            <img src="<%=@case.social_worker.image_url%>" class="img-fluid img-thumbnail" alt="Client Picture">
            <h3><%= link_to @case.social_worker.name, social_worker_path(@case.social_worker)%></h3>
        </div>
    </div>
    <u>
        <h1 class="display-4 text-left">Resource</h1>
    </u>
    <h3><%= link_to @case.resource.name, resource_path(@case.resource)%></h3>

    <u>
        <h1 class="display-4 text-left">Focus</h1>
    </u>
    <h3><%=@case.focus%></h3>

    <u>
        <h1 class="display-4 text-left">Status</h1>
    </u>
    <h3><%=@case.status%></h3>

    <u>
        <h1 class="display-4 text-left">Notes</h1>
    </u>
    <ul>
        <% @case.notes.each do |note| %>
        <div class="card">
            <h5 class="card-header"><%= note.format_time %> by <%= note.created_by %></h5>
            <div class="card-body">
                <p class="card-text"><%= note.content %></p>
                <form method="post" action='/notes/<%=note.id%>'>
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <input type="hidden" name="id" value="<%=note.id%>">
                    <input type="submit" value="Delete" class="btn btn-primary">
                </form>
            </div>
        </div>
        <% end %>
    </ul>

    <form action='/notes' method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="note[case_id]" value="<%= @case.id %>">
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Notes</span>
            </div>
            <textarea class="form-control" aria-label="With textarea" name="note[content]"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit Note</button>
    </form><br>
    <hr>
    <a class="btn btn-primary" href="/cases/<%=@case.id%>/edit" role="button">Edit Case</a><br><br>

    <form method="post" action='/cases/<%=@case.id%>/close'>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="id" value="<%=@case.id%>">
        <input type="submit" value="Close Case" class="btn btn-primary"><br><br>
    </form>
</div>
</div>
</div>